version: '3'

services:
  postgresql:
    container_name: ninjaone-rmm_services_server_app-postgresql
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_USER=rmm
      - POSTGRES_PASSWORD=rmm

  java:
    container_name: ninjaone-rmm_services_server_app-java
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8030:8080"
    volumes:
      - .:/app:delegated
    env_file:
      - .env
    tty: true
    depends_on:
      - postgresql

volumes:
  postgres_data:
